### ISSUE TITLE
Running PeVerify produces  error

### ISSUE THREAD

**Issue by SimonCropp** [Codealike/arrayslice#8]
Running PEverify on the output of this https://github.com/Fody/FodyAddinSamples/tree/master/ArraySlicesSample

Results in 

```
Error	4	Fody: PEVerify of the assembly failed.

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\Code\Fody\FodyAddinSamples\ArraySlicesSample\bin\Debug\ArraySlicesSample.dll : AsyncErrorHandlerSample::Run][offset 0x0000005A] Unable to resolve token.
1 Error(s) Verifying C:\Code\Fody\FodyAddinSamples\ArraySlicesSample\bin\Debug\ArraySlicesSample.dll
	ArraySlicesSample
```

**Comment by redknightlois** [comment]
Will take a look at this during the week. The strange thing is that PeVerify doesnt complain on the tests (which are very similar to what we have there).

**Comment by SimonCropp** [comment]
do u remember to remove the reference?

**Comment by redknightlois** [comment]
Which reference?

**Comment by SimonCropp** [comment]
perhaps u dont want to do this https://github.com/Codealike/arrayslice/blob/master/NuGet/install.ps1#L71

**Comment by redknightlois** [comment]
Indeed, I don't want to do that... In fact, I want it to be exactly the other way around.

**Comment by SimonCropp** [comment]
well true is the default done by nuget. so u can just remove that code. for most weavers it makes sense since the reference is only for intellisense at compile time and not needed at runtime

**Comment by redknightlois** [comment]
Fixed. I included a PR for it.
